# Generated by Django 4.2.7 on 2023-11-06 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_feed', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ачивка пользователя', 'verbose_name_plural': 'Ачивки пользователей'},
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_feed.achievement', verbose_name='Ачивка'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получил ачивку'),
        ),
    ]
